import json

path = "inputs/seeds/lop-9/dai-so/lop-b/tuan05-pt-va-he-pt-bac-nhat-hai-an/phieu-b-pt-va-he-pt-bac-nhat-hai-an.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

for stage in data["stages"]:
    if stage["kind"] == "practice1":
        # Bài 1
        stage["blocks"][1]["statement"] = "Trả lời Đúng (Đ) / Sai (S): [[br]] \\begin{minipage}[t]{0.47\\linewidth} a) $2x+3y=5$ là PT bậc nhất hai ẩn. [[br]] b) $x^2+y=1$ là PT bậc nhất hai ẩn. [[br]] c) $(1;1)$ là nghiệm của $2x+3y=5$. \\end{minipage}\\hfill\\begin{minipage}[t]{0.47\\linewidth} d) $(2;0)$ là nghiệm của $2x+3y=5$. [[br]] e) $(0;2)$ là nghiệm của $x-y=-2$. [[br]] f) $(1;3)$ là nghiệm của $x+y=4$. \\end{minipage}"
        stage["blocks"][1]["writelines"] = 2
        # Bài 2
        stage["blocks"][2]["statement"] = "Kiểm tra cặp số có là nghiệm của hệ không: [[br]] a) $(1;0)$ với hệ $\\begin{cases} x+2y=1 \\\\ 3x-2y=3 \\end{cases}$ [[br]] b) $(3;-1)$ với hệ $\\begin{cases} x+2y=1 \\\\ 3x-2y=3 \\end{cases}$ [[br]] c) $(1;0)$ với hệ $\\begin{cases} x+y=1 \\\\ x-y=1 \\end{cases}$ [[br]] d) $(2;1)$ với hệ $\\begin{cases} x+y=3 \\\\ x-y=1 \\end{cases}$"
        # Bài 3
        stage["blocks"][5]["statement"] = "a) Viết nghiệm tổng quát của $x+y=3$. [[br]] b) Hoàn thành bảng nghiệm của $x+y=3$ tại $x=0;\\,1;\\,3$. [[br]] c) Viết nghiệm tổng quát của $2x-y=1$. [[br]] d) Tìm một nghiệm nguyên dương của $x+y=3$. [[br]] e) PT $0x+y=2$ có tập nghiệm là đường thẳng nào?"
        stage["blocks"][5]["writelines"] = 4
        stage["solution"] = "\\textbf{Bài 1:} a) Đ; b) S (có $x^2$); c) Đ ($2+3=5$); d) S ($4\\neq 5$); e) Đ ($0-2=-2$); f) Đ ($1+3=4$). [[br]] \\textbf{Bài 2:} a) $1+0=1$ ✓, $3-0=3$ ✓ $\\Rightarrow$ là nghiệm. [[br]] b) $3-2=1$ ✓, $9+2=11\\neq 3$ $\\Rightarrow$ không. [[br]] c) $1$ ✓, $1$ ✓ $\\Rightarrow$ là nghiệm. [[br]] d) $3$ ✓, $1$ ✓ $\\Rightarrow$ là nghiệm. [[br]] \\textbf{Ví dụ mẫu:} một đường thẳng. [[br]] \\textbf{Bài 3:} a) $y=3-x$, nghiệm $(x;\\,3-x)$, $x\\in\\mathbb{R}$. [[br]] b) $x=0\\to y=3$; $x=1\\to y=2$; $x=3\\to y=0$. [[br]] c) $(x;\\,2x-1)$. [[br]] d) ví dụ $(1;2)$ hoặc $(2;1)$. [[br]] e) đường thẳng $y=2$ (nằm ngang)."
    elif stage["kind"] == "practice2":
        stage["blocks"][1]["statement"] = "Mua $2$ cái bút và $3$ quyển vở hết $32$ nghìn đồng; mua $4$ cái bút và $1$ quyển vở hết $24$ nghìn đồng. Gọi giá một bút là $x$, một vở là $y$ (nghìn đồng, $x,y>0$). [[br]] [NB] a) Biểu diễn số tiền mua $2$ cái bút và $3$ quyển vở theo $x$ và $y$. [[br]] [NB] b) Biểu diễn số tiền mua $4$ cái bút và $1$ quyển vở theo $x$ và $y$. [[br]] [TH] c) Lập phương trình thứ nhất từ dữ kiện $32$ nghìn đồng. [[br]] [TH] d) Lập phương trình thứ hai từ dữ kiện $24$ nghìn đồng. [[br]] [VD] e) Viết hệ phương trình và giải tìm $x, y$."
        stage["blocks"][2]["statement"] = "Vừa gà vừa chó đếm được $35$ con và $94$ chân. Gọi số gà $x$, số chó $y$ ($x,y$ nguyên dương). [[br]] [NB] a) Lập phương trình thể hiện tổng số con là $35$. [[br]] [NB] b) Biểu diễn số chân gà theo $x$. [[br]] [NB] c) Biểu diễn số chân chó theo $y$. [[br]] [TH] d) Lập phương trình thể hiện tổng số chân là $94$. [[br]] [TH] e) Viết hệ phương trình và giải tìm số gà, số chó."
        stage["blocks"][4]["statement"] = "Một cửa hàng bán kẹo loại A giá $6$ nghìn/gói và loại B giá $10$ nghìn/gói. Bạn Minh mua tổng cộng $8$ gói cả hai loại hết đúng $60$ nghìn đồng. Gọi số gói A là $x$, số gói B là $y$. [[br]] [NB] a) Lập phương trình thể hiện tổng số gói kẹo. [[br]] [NB] b) Biểu diễn số tiền mua kẹo loại A và loại B theo $x$ và $y$. [[br]] [TH] c) Lập phương trình thể hiện tổng số tiền là $60$ nghìn đồng. [[br]] [TH] d) Giải hệ phương trình và kết luận."
        stage["blocks"][5]["statement"] = "Trộn dung dịch loại I (nồng độ $10\\%$) với dung dịch loại II (nồng độ $30\\%$) để được $200$ g dung dịch nồng độ $25\\%$. Gọi khối lượng loại I là $x$ (g), loại II là $y$ (g). [[br]] [NB] a) Viết phương trình tổng khối lượng hai dung dịch. [[br]] [NB] b) Tính lượng chất tan trong $x$ gam loại I và $y$ gam loại II. [[br]] [TH] c) Tính lượng chất tan trong $200$ g dung dịch $25\\%$. [[br]] [TH] d) Lập phương trình tổng lượng chất tan. [[br]] [VD] e) Viết hệ phương trình hoàn chỉnh. [[br]] [VDC] f) Giải hệ và đối chiếu điều kiện để kết luận."
        stage["solution"] = "\\textbf{Bài 4:} a) $2x+3y$. b) $4x+y$. c) $2x+3y=32$. d) $4x+y=24$. e) Hệ $\\begin{cases} 2x+3y=32 \\\\ 4x+y=24 \\end{cases}$. Từ PT hai rút $y=24-4x$ thế vào PT đầu $\\Rightarrow 2x+3(24-4x)=32 \\Rightarrow -10x=-40 \\Rightarrow x=4, y=8$. Giá bút $4$k, vở $8$k. [[br]] \\textbf{Bài 5:} a) $x+y=35$. b) $2x$. c) $4y$. d) $2x+4y=94$. e) Hệ $\\begin{cases} x+y=35 \\\\ 2x+4y=94 \\end{cases} \\Rightarrow x=35-y \\Rightarrow 2(35-y)+4y=94 \\Rightarrow y=12, x=23$. Vậy $23$ gà, $12$ chó. [[br]] \\textbf{Bài 6:} a) $x+y=8$. b) Loại A: $6x$, loại B: $10y$. c) $6x+10y=60$. d) Hệ $\\begin{cases} x+y=8 \\\\ 6x+10y=60 \\end{cases} \\Rightarrow 6x+10(8-x)=60 \\Rightarrow -4x=-20 \\Rightarrow x=5, y=3$. Mua $5$ gói A, $3$ gói B. [[br]] \\textbf{Bài 7:} a) $x+y=200$. b) Loại I: $0{,}1x$, loại II: $0{,}3y$. c) $200 \\cdot 0{,}25=50$ (g). d) $0{,}1x+0{,}3y=50$. e) Hệ $\\begin{cases} x+y=200 \\\\ 0{,}1x+0{,}3y=50 \\end{cases}$. f) Thế $x=200-y \\Rightarrow 0{,}1(200-y)+0{,}3y=50 \\Rightarrow 0{,}2y=30 \\Rightarrow y=150, x=50$. Dùng $50$ g loại I và $150$ g loại II."
    elif stage["kind"] == "reflection":
        stage["blocks"][1]["statement"] = "Đúng (Đ) / Sai (S): [[br]] \\begin{minipage}[t]{0.47\\linewidth} a) $4x-y=2$ là PT bậc nhất hai ẩn. [[br]] b) $xy=1$ là PT bậc nhất hai ẩn. [[br]] c) $(2;1)$ là nghiệm của $x+y=3$. [[br]] d) $(1;2)$ là nghiệm của $2x-y=0$. \\end{minipage}\\hfill\\begin{minipage}[t]{0.47\\linewidth} e) $(0;3)$ là nghiệm của $x+y=3$. [[br]] f) $(1;1)$ là nghiệm của hệ $\\begin{cases} x+y=2 \\\\ x-y=0 \\end{cases}$. [[br]] g) $(2;2)$ là nghiệm của $x-y=0$. \\end{minipage}"
        stage["blocks"][2]["statement"] = "a) Viết nghiệm tổng quát của $x+y=5$. [[br]] b) Hoàn thành bảng nghiệm của $x+y=5$ tại $x=0;\\,2;\\,5$. [[br]] c) Viết nghiệm tổng quát của $3x-y=2$. [[br]] d) Tìm một nghiệm nguyên dương của $2x+y=6$. [[br]] e) Tập nghiệm của $x=4$ là đường thẳng nào?"
        stage["blocks"][3]["statement"] = "Một mảnh đất hình chữ nhật có chu vi $200$ m, chiều dài hơn chiều rộng $20$ m. Gọi chiều dài $x$, chiều rộng $y$ (m). [[br]] [NB] a) Công thức tính nửa chu vi hình chữ nhật theo $x$ và $y$ là gì? [[br]] [NB] b) Lập phương trình từ dữ kiện nửa chu vi. [[br]] [NB] c) Lập phương trình chiều dài hơn chiều rộng $20$ m. [[br]] [TH] d) Viết hệ phương trình. [[br]] [TH] e) Giải hệ bằng phương pháp cộng đại số (hoặc thế). [[br]] [TH] f) Kết luận."
        stage["blocks"][4]["statement"] = "Lớp 9A có $40$ học sinh. Số học sinh nam nhiều hơn số học sinh nữ $4$ bạn. Gọi số nam $x$, số nữ $y$. [[br]] [NB] a) Lập phương trình tổng số học sinh. [[br]] [NB] b) Lập phương trình số nam hơn số nữ. [[br]] [TH] c) Lập hệ phương trình. [[br]] [TH] d) Trình bày bước giải hệ. [[br]] [VD] e) Kết luận số lượng học sinh."
        stage["blocks"][5]["statement"] = "Trộn $x$ lít dung dịch loại I ($20\\%$ muối) với $y$ lít loại II ($50\\%$ muối) được $300$ lít dung dịch $40\\%$ muối. [[br]] [NB] a) Viết phương trình tổng thể tích hai loại dung dịch. [[br]] [NB] b) Biểu diễn lượng muối trong dung dịch loại I. [[br]] [NB] c) Biểu diễn lượng muối trong dung dịch loại II. [[br]] [TH] d) Tính lượng muối trong dung dịch mới. [[br]] [TH] e) Lập phương trình tổng lượng muối. [[br]] [VD] f) Viết hệ phương trình hoàn chỉnh. [[br]] [VDC] g) Giải hệ và kết luận."
        stage["solution"] = "\\textbf{Bài 8:} a) Đ; b) S (có $xy$); c) Đ; d) Đ ($2-2=0$); e) Đ; f) Đ ($2$ ✓, $0$ ✓); g) Đ. [[br]] \\textbf{Bài 9:} a) $(x;\\,5-x)$. b) $x=0\\to y=5$; $x=2\\to y=3$; $x=5\\to y=0$. c) $(x;\\,3x-2)$. d) ví dụ $(1;4),(2;2)$. e) đường thẳng $x=4$ (thẳng đứng). [[br]] \\textbf{Bài 10:} a) $x+y$. b) $x+y=100$. c) $x-y=20$. d) Hệ $\\begin{cases} x+y=100 \\\\ x-y=20 \\end{cases}$. e) Cộng hai vế $\\Rightarrow 2x=120 \\Rightarrow x=60, y=40$. f) Dài $60$ m, rộng $40$ m. [[br]] \\textbf{Bài 11:} a) $x+y=40$. b) $x-y=4$. c) Hệ $\\begin{cases} x+y=40 \\\\ x-y=4 \\end{cases}$. d) $2x=44 \\Rightarrow x=22, y=18$. e) Có $22$ nam, $18$ nữ. [[br]] \\textbf{Bài 12:} a) $x+y=300$. b) $0{,}2x$. c) $0{,}5y$. d) $300 \\cdot 0{,}4 = 120$. e) $0{,}2x+0{,}5y=120$. f) Hệ $\\begin{cases} x+y=300 \\\\ 0{,}2x+0{,}5y=120 \\end{cases}$. g) Thế $x=300-y \\Rightarrow 0{,}2(300-y)+0{,}5y=120 \\Rightarrow y=200, x=100$. Dùng $100$ lít loại I, $200$ lít loại II."

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
